"""Fix

Revision ID: b9940d7b1091
Revises: 02478abfd4ce
Create Date: 2023-11-20 14:23:38.737441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9940d7b1091'
down_revision: Union[str, None] = '02478abfd4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ratings_image_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'images', ['image_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_image_id_fkey', 'ratings', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
