"""Fix

Revision ID: bab727219414
Revises: cd22a0f5db75
Create Date: 2023-11-20 15:02:33.631677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab727219414'
down_revision: Union[str, None] = 'cd22a0f5db75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_owner_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_owner_id_fkey', 'images', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
