"""Add username

Revision ID: da9ac51fd43a
Revises: e0b1e4b2b0d4
Create Date: 2023-11-18 12:53:48.857957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'da9ac51fd43a'
down_revision: Union[str, None] = 'e0b1e4b2b0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=1024), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###
    permissions_temp_table = table(
        "permissions",
        column("id", sa.Integer),
        column("role_name", sa.String),
        column("can_add_image", sa.Boolean),
        column("can_update_image", sa.Boolean),
        column("can_delete_image", sa.Boolean),
        column("can_add_tag", sa.Boolean),
        column("can_update_tag", sa.Boolean),
        column("can_delete_tag", sa.Boolean),
        column("can_add_comment", sa.Boolean),
        column("can_update_comment", sa.Boolean),
        column("can_delete_comment", sa.Boolean),
    )
    
    op.bulk_insert(
        permissions_temp_table,
        [
            {
                "id": 1,
                "role_name": "User",
                "can_add_image": True,
                "can_update_image": False,
                "can_delete_image": False,
                "can_add_tag": True,
                "can_update_tag": False,
                "can_delete_tag": False,
                "can_add_comment": True,
                "can_update_comment": False,
                "can_delete_comment": False,
            },
            {
                "id": 2,
                "role_name": "Moderator",
                "can_add_image": True,
                "can_update_image": False,
                "can_delete_image": True,
                "can_add_tag": True,
                "can_update_tag": True,
                "can_delete_tag": True,
                "can_add_comment": True,
                "can_update_comment": True,
                "can_delete_comment": False,
            },
            {
                "id": 3,
                "role_name": "Admin",
                "can_add_image": True,
                "can_update_image": True,
                "can_delete_image": True,
                "can_add_tag": True,
                "can_update_tag": True,
                "can_delete_tag": True,
                "can_add_comment": True,
                "can_update_comment": True,
                "can_delete_comment": True,
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
